/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityAction: typeof import('./src/components/activityAction.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui')['ActionSheet']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutDialog: typeof import('@nutui/nutui')['Dialog']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutProgress: typeof import('@nutui/nutui')['Progress']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulesDialog: typeof import('./src/components/rulesDialog.vue')['default']
    SubmitFrom: typeof import('./src/components/submitFrom.vue')['default']
  }
}
